# Generated by Django 5.2 on 2025-11-01 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='expanation',
            new_name='explanation',
        ),
    ]
